### ISSUE TITLE
apt cookbook upgrade breaks preferences_resourse 

### ISSUE THREAD

**Issue by fsultan** [reaktor/chef-debian#16]
apt v2.7.0 added a regex validation for package_name that doesn't allow '*'
https://github.com/opscode-cookbooks/apt/commit/d9da7847c58d156ad1e24021d49511efdce0394d

providers/repository.rb defines:
```
def preferences_resourse(exec_action)
  apt_preference new_resource.repo_name do
    package_name '*'
```

example error:
[2015-05-22T13:26:13+00:00] ERROR: debian_repository[backports] (debian::backports line 22) had an error: Chef::Exceptions::ValidationFailed: Option package_name's value * does not match regular expression [/^([a-z]|[A-Z]|[0-9]|_|-|\.)+$/]

**Comment by tmatilai** [comment]
Thanks for the report and sorry for the late answer. I'll try to revisit this cookbook soonish. Also to verify that everything works with jessie and current testing.

**Comment by tmatilai** [comment]
This is fixed in master if you want to test. I'll cut a release tomorrow.
